name: Cypress Cloud Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.13.1
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Cypress run with Dashboard
      run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
      env:
        # Use GitHub Actions variables for better Cypress Cloud integration
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        
    - name: Create reports branch with dashboard link
      if: always()
      run: |
        # Configure git
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create new branch or switch to it
        git fetch origin reports || true
        git checkout reports || git checkout -b reports
        
        # Create reports directory if it doesn't exist
        mkdir -p github-pages
        
        # Create index page with link to Cypress Cloud
        echo "<!DOCTYPE html>
        <html>
        <head>
            <title>Cypress Test Reports</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #333; }
                .report-link { margin: 10px 0; }
            </style>
        </head>
        <body>
            <h1>Cypress Test Reports</h1>
            <div class='report-link'>
                <a href='https://dashboard.cypress.io/projects/your-project-id-here/runs'>View Test Results in Cypress Cloud</a>
            </div>
        </body>
        </html>" > github-pages/index.html
        
        # Add all files
        git add -A
        
        # Commit changes
        git commit -m "Add test report link from GitHub Actions run ${GITHUB_RUN_ID}" || echo "No changes to commit"
        
        # Push to reports branch
        git push origin reports
        
    - name: Update PR description with report link
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          const { owner, repo, number } = context.issue;
          const reportUrl = `https://dashboard.cypress.io/projects/your-project-id-here/runs`;
          
          // Get current PR description
          const { data: pullRequest } = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          
          let body = pullRequest.body || '';
          
          // Add report link if not already present
          if (!body.includes('Test Report')) {
            body += `\n\n## Test Report\n[View the Cypress Test Results](${reportUrl})`;
            
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: number,
              body,
            });
          }
